spring:
  config:
    activate:
      on-profile: prod


  datasource:
    url: jdbc:mysql://${RDB_HOST}:${RDB_PORT}/${RDB_SCHEMA}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
    username: ${RDB_USER}
    password: ${RDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-time: 3600000 # 1 hour = 1000 * 60 * 60
  refresh-token-expiration-time: 86400000 # 1 day = 1000 * 60 * 60 * 24
  registration-token-expiration-time: 86400000 # 1 day = 1000 * 60 * 60 * 24

seoul-open-api:
  key: ${SEOUL_OPEN_API_KEY}

neis-open-api:
  key: ${NEIS_OPEN_API_KEY}

key:
  openai:
    api-key: ${OPENAI_API_KEY}
  ncp:
    ocr-key: ${NCP_OCR_API_KEY}

---

spring:
  config:
    activate:
      on-profile: default


  datasource:
    url: jdbc:mysql://localhost:3306/asap?serverTimezone=Asia/Seoul&useSSL=false&rewriteBatchedStatements=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true

jwt:
  secret: "testSecrettestSecrettestSecrettestSecrettestSecret"
  access-token-expiration-time: 86400000
  refresh-token-expiration-time: 86400000
  registration-token-expiration-time: 86400000

seoul-open-api:
  key: "key"

neis-open-api:
  key: "key"


key:
  openai:
    api-key: "key"
  ncp:
    ocr-key: "key"