version: '3.8'

services:
  asap-backend:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest
    container_name: asap-backend
    ports:
      - "8080:8080"
      - "8079:8079"
    networks:
      - asap-backend
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul

networks:
  asap-backend:
    name: asap-backend
    external: true